### ISSUE TITLE
Feature Request: Player character generator

### ISSUE THREAD

**Issue by yjeroen** [TheDude-gh/diablo2graphics#1]
What an amazing tool you build!

Any chance you could also create this for player characters?

**Comment by TheDude-gh** [comment]
Thanks.

It is over 2 years since I worked on this and it was just fun project to see, if I am able to do it.

As far as I remember, characters data is practically the same as monsters data, only characters have 16 directions instead of only 8. So probably it wouldn't be that much work to do and sure, it would be nice to generate any character-armor-weapon combination.

If I were to work on this it wouldn't be near future, but who knows, maybe one day. 
The code is free to use, so maybe someone else could step in too.

**Comment by TheDude-gh** [comment]
I made it quite sooner after all.

Support for character sprites added in 33972e9d1d45dc796c0c95dbce98c59ff97ab1a5

**Comment by yjeroen** [comment]
Very cool, thanks!!

Something weird is happening with the skin however, for example sorceress I can't see the combination to get pink skin? I tried all palette and remap options.

![image](https://user-images.githubusercontent.com/1303988/151776229-c7bd022f-dcca-454d-85fb-f1245a469cc2.png)

![image](https://user-images.githubusercontent.com/1303988/151776267-7f2c7fce-349f-40d3-9225-41d52938beb4.png)
